import { Fragment, useState, useEffect } from 'react';
import Head from 'next/head';

// Components
import Welcome from '../components/sections/home/Welcome';
import About from '../components/sections/home/About';

const Home = () => {
  useEffect(() => {
    window.onscroll = function (e) {
      // print "false" if direction is down and "true" if up
      console.log(this.oldScroll > this.scrollY);
      this.oldScroll = this.scrollY;
    };
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Cloud Studio Ltd</title>
        <meta name='description' content='Generated by create next app' />
        <meta charSet='UTF-8' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Kanit:wght@500&display=swap'
          rel='stylesheet'
        ></link>
        {/* Materialize css */}
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'
        />
      </Head>
      <body>
        <Welcome />
        <About />

        <script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js'></script>
      </body>
    </Fragment>
  );
};

export default Home;
